export const SEND_SUPPORT = 'SEND_SUPPORT';
export const FETCH_AUTH_DATA = 'FETCH_AUTH_DATA';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const LOGOUT = 'LOGOUT';