export const ENTITY_FORM_ADD_SUGGESTION = 'ENTITY_FORM_ADD_SUGGESTION';
export const ENTITY_FORM_SELECT_SUGGESTION = 'ENTITY_FORM_SELECT_SUGGESTION';
export const ENTITY_FORM_ADD_VAL_TO_HIDDEN_FIELD = 'ENTITY_FORM_ADD_VAL_TO_HIDDEN_FIELD';