export const MT_ENTITY_ADD = 'MT_ENTITY_ADD';
export const MT_EDITABLE_ENTRY_SAVE = 'MT_EDITABLE_ENTRY_SAVE';
export const MT_EDITABLE_ENTRY_DELETE = 'MT_EDITABLE_ENTRY_DELETE';
export const MT_EDITABLE_ENTRY_CLOSE = 'MT_EDITABLE_ENTRY_CLOSE';